// Jargon.ts: Just a bunch of nonsense.

/**
 * Array of random jargon phrases for fun status messages.
 */
export const JARGON_PHRASES = [
  "RECALIBRATING FLUX CAPACITORS",
  "OPTIMIZING QUANTUM FOAM DENSITY",
  "********",
  "RETICULATING SPLINES...",
  "REVERSING POLARITY OF NEUTRON FLOW",
  "ADJUSTING BELL CURVES",
  "NORMALIZING POWER GRID",
  "TRIANGULATING POSITION OF SATELLITES",
  "DOWNLOADING MORE RAM",
  "********",
  "COMPRESSING FISH FILES",
  "GENERATING WITTY DIALOG!",
  "SPINNING UP HAMSTER WHEELS",
  "CONSULTING MAGIC 8-BALL",
  "INITIALIZING CHAOS ENGINE",
  "========",
  "DEFRAGMENTING SOCIAL LIFE",
  "CALCULATING LLAMA EXPECTORATION TRAJECTORY",
  "GROOMING AUTOMATED GARDEN GNOMES",
  "1 + 1 = 11",
  "ALIGNING COVARIANCE MATRICES...",
  "PERTURBING MATRICES",
  "ASSERTING PACKED EXEMPLARS",
  "ATTEMPTING TO LOCK BACK-BUFFER",
  "********",
  "BUILDING DATA TREES",
  "CALCULATING INVERSE PROBABILITY MATRICES",
  "TOKENIZING REAL LIFE...",
  "...",
  "BENDING THE SPOON",
  "FILTERING MORALE",
  "SYNTHESIZING GRAVITY",
  "BREEDING FAUNA",
  "LECTURING ERRANT SUBSYSTEMS",
  "...",
  "SPINNING VIOLENTLY AROUND Y-AXIS",
  "TESTING MIDDLE WARE",
  "========",
  "TIME-COMPRESSING SIMULATOR CLOCK",
  "REMOVING TEXTURE GRADIENTS...",
  "ROUTING NEURAL NETWORK INFANSTRUCTURE",
  "CHECKING FOR TERMINATION CONDITIONS",
  "========",
  "GATHERING PARTICLE SOURCES",
  "OBFUSCATING QUIGLEY MATRIX...",
  "--------------",
];

/**
 * Returns a random jargon phrase from the JARGON_PHRASES array.
 */
export function getRandomJargon(): string {
  return JARGON_PHRASES[Math.floor(Math.random() * JARGON_PHRASES.length)];
}
